# Generated by Django 6.0.1 on 2026-02-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('activity_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('winner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Student Activities',
                'db_table': 'student_activity',
            },
        ),
    ]
