# Generated by Django 6.0.1 on 2026-02-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
                ('post', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Tester', 'Tester'), ('HR', 'HR')], max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
