# Generated by Django 6.0.1 on 2026-02-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
