# Generated by Django 6.0.1 on 2026-02-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_remove_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Course',
                'db_table': 'course',
            },
        ),
    ]
