# Generated by Django 6.0.1 on 2026-02-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.course')),
            ],
            options={
                'verbose_name_plural': 'Studenttable',
                'db_table': 'studenttable',
            },
        ),
    ]
