# Generated by Django 6.0.1 on 2026-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty')], max_length=20, null=True),
        ),
    ]
