# Generated by Django 6.0.1 on 2026-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
