# Generated by Django 6.0.1 on 2026-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcutStock',
            new_name='productStock',
        ),
        migrations.AddField(
            model_name='product',
            name='productColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.BooleanField(default=True),
        ),
    ]
