# Generated by Django 6.0.1 on 2026-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_prodcutstock_product_productstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=50)),
                ('carPrice', models.PositiveIntegerField()),
                ('carCompany', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
