# Generated by Django 6.0.1 on 2026-02-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.TimeField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentAmount', models.IntegerField()),
                ('paymentDate', models.DateField()),
                ('paymentTime', models.TimeField()),
                ('bookingId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
