# Generated by Django 6.0.1 on 2026-02-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_booking_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerid', models.AutoField(primary_key=True, serialize=False)),
                ('offerName', models.CharField(max_length=100)),
                ('offerDescription', models.TextField()),
                ('offerValidfrom', models.DateField()),
                ('offerValidto', models.DateField()),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('offerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.offer')),
            ],
            options={
                'db_table': 'bookingorder',
            },
        ),
    ]
