# Generated by Django 6.0.1 on 2026-02-06 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_offer_bookingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerPhone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateField()),
                ('purchaseAmount', models.FloatField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
