# Generated by Django 6.0.1 on 2026-02-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('vehicleType', models.CharField()),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('vehicleModel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('providerId', models.AutoField(primary_key=True, serialize=False)),
                ('garageName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('opennigTime', models.TimeField()),
                ('closingTime', models.TimeField()),
                ('rating', models.FloatField()),
                ('approvalStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')])),
            ],
            options={
                'db_table': 'serviceprovider',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userFullName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=10)),
                ('userRole', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('Service Provider', 'Service Provider')], max_length=20)),
                ('userAddress', models.TextField(max_length=200)),
                ('userCity', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userStatus', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')])),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('bookingStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')])),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.customers')),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.serviceprovider')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceNumber', models.CharField(max_length=20)),
                ('invoiceDate', models.DateField()),
                ('totalAmount', models.FloatField()),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.bookings')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')])),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')])),
                ('paymentDate', models.DateTimeField()),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.bookings')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=100)),
                ('serviceDescription', models.TextField()),
                ('servicePrice', models.FloatField()),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.serviceprovider')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='serviceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.services'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.user'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_eGarage.user'),
        ),
    ]
